timezone: "America/New_York"

keywords:
  family: ["kid","kids","family","farm","farmers","market","festival","pumpkin","hayride","art in the park","library","storytime","parade","scarecrow","macaroni kid"]
  adult:  ["tavern","brewery","happy hour","trivia","live music","band","wine","cider","theatre","comedy","dj","open mic","karaoke","restaurant"]
  recurring: ["every ","weekly","wednesdays","thursdays","fridays","saturdays","sundays","mondays","tuesdays","first ","second ","third ","last "]

# APIs you enabled
enable_facebook: false
enable_eventbrite: true
enable_bandsintown: false

# prefer GitHub Action secrets; these can be blank here
eventbrite_token: ""
bandsintown_app_id: ""

user_agent: "fxbg-event-bot/1.0 (+https://example.com)"
throttle_seconds_min: 2
throttle_seconds_max: 5
headless_js_timeout: 0
max_future_days: 365

# Route sports to a separate sports.ics
route_to_sports:
  # UMW Athletics hosts + their calendar mirror
  domains:
    - umweagles.com
    - at.umw.edu
  # Titles that look like sports
  title_regex:
    - '(?i)\b(University of Mary Washington|UMW)\b.*\b(Soccer|Basketball|Baseball|Softball|Lacrosse|Tennis|Volleyball|Swimming|Track|Field Hockey|Rugby|XC|Cross[- ]Country)\b'
    - '(?i)\b(Coast[- ]to[- ]Coast|C2C|NCAA)\b.*\b(Tournament|Championship)\b'
  # Optional globs (simpler matching)
  title_glob:
    - '* vs *'
    - '* at *'
  # If a venue name implies a sports facility
  location_regex:
    - '(?i)\b(Stadium|Field|Court|Gym|Arena|Track|Pool)\b'



# --- new sources: FCPS District + Gladys West Elementary ---
sources:
  # --- FXBG tourism/events (HTML crawler) ---
  - name: FXBG Events
    type: fxbg
    url: https://fxbg.com/events/

  # --- Spotsylvania Towne Centre (HTML crawler) ---
  - name: Spotsylvania Towne Centre
    type: spotsy_townecentre
    url: https://www.spotsylvaniatownecentre.com/events/

  # --- Spotsylvania ICS category feeds (CivicEngage) ---
  - name: Spotsy Calendar catID 50
    type: ics
    url: https://www.spotsylvania.va.us/common/modules/iCalendar/iCalendar.aspx?catID=50&feed=calendar

  - name: Spotsy Calendar catID 23
    type: ics
    url: https://www.spotsylvania.va.us/common/modules/iCalendar/iCalendar.aspx?catID=23&feed=calendar

  - name: Spotsy Calendar catID 66
    type: ics
    url: https://www.spotsylvania.va.us/common/modules/iCalendar/iCalendar.aspx?catID=66&feed=calendar

  - name: Spotsy Calendar catID 54
    type: ics
    url: https://www.spotsylvania.va.us/common/modules/iCalendar/iCalendar.aspx?catID=54&feed=calendar

  # Fredericksburg City Public Schools (district) events page
  - name: "FCPS District Events"
    type: html
    url: "https://www.fxbgschools.us/events"
    html:
      item: "ul.lm-events li, .events-list li, article, li.event"
      title: "a"
      date: "time[datetime]"
      # description/location selectors are optional; parse_when() will handle dates
      # location: ".event-venue, .event-location"

  # Gladys West Elementary events page
  - name: "Gladys West Elementary Events"
    type: thrillshare_ical
    url: "https://gwes.fxbgschools.us/o/gwes/events"
    html:
      item: "ul.lm-events li, .events-list li, article, li.event"
      title: "a"
      date: "time[datetime]"

  # ------------------------------
  # City of Fredericksburg (CivicEngage) — official ICS feeds
  # iCalendar index (reference): https://www.fredericksburgva.gov/iCalendar.aspx
  # ------------------------------
  - name: "City of Fredericksburg — Main (ICS)"
    type: "ics"
    url: "https://www.fredericksburgva.gov/common/modules/iCalendar/iCalendar.aspx?catID=35&feed=calendar"

  - name: "City of Fredericksburg — Parks & Rec Programs (ICS)"
    type: "ics"
    url: "https://www.fredericksburgva.gov/common/modules/iCalendar/iCalendar.aspx?catID=22&feed=calendar"

  - name: "City of Fredericksburg — Special Events (ICS)"
    type: "ics"
    url: "https://www.fredericksburgva.gov/common/modules/iCalendar/iCalendar.aspx?catID=47&feed=calendar"

  - name: "Spotsylvania County — Parks & Recreation (ICS)"
    type: "ics"
    url: "https://www.spotsylvania.va.us/common/modules/iCalendar/iCalendar.aspx?catID=23&feed=calendar"

  - name: "Spotsylvania County — Tourism (ICS)"
    type: "ics"
    url: "https://www.spotsylvania.va.us/common/modules/iCalendar/iCalendar.aspx?catID=29&feed=calendar"

  - name: "King George — Events (ICS)"
    type: "ics"
    url: "https://www.kinggeorgecountyva.gov/common/modules/iCalendar/iCalendar.aspx?catID=29&feed=calendar"

  - name: "King George — Parks & Recreation (ICS)"
    type: "ics"
    url: "https://www.kinggeorgecountyva.gov/common/modules/iCalendar/iCalendar.aspx?catID=61&feed=calendar"

  - name: "King George — Library (RSS)"
    type: "rss"
    url: "https://www.kinggeorgecountyva.gov/calendar.aspx?CID=62"

  - name: "King George — Cooper. Extension / Farmers Market (RSS)"
    type: "rss"
    url: "https://www.king-george.va.us/calendar.aspx?CID=64"

  - name: Macaroni KID Fredericksburg
    type: "macaronikid_fxbg"

  # You can add more City calendars later by copying their ICS link from the iCalendar page.

  # ------------------------------
  # University of Mary Washington (Concept3D/Localist)
  # “Save to RSS” master feed from the All-Events page
  # ------------------------------
  - name: "UMW — All Events (RSS)"
    type: "rss"
    url: "https://at.umw.edu/calendar/1.xml"

  # ------------------------------
  # Local media calendar (scrape-friendly HTML)
  # ------------------------------
  - name: "Fredericksburg Free Press — Local Events"
    type: "freepress"
    url: "https://www.fredericksburgfreepress.com/calendar/"
    html:
      item: "article, .tribe-events-calendar-list__event, .event, .hentry, li"
      title: "h2, h3, .entry-title, a"
      date: "time[datetime], time, .date, .tribe-event-date-start"
      time: "time[datetime], time, .tribe-event-time"
      location: ".tribe-venue, .location, .venue, .place, .em-location, p"
      description: "p, .entry-summary, .tribe-events-list-event-description"

  # ------------------------------
  # Event platforms (APIs)
  # ------------------------------
  - name: "Eventbrite — Fredericksburg, VA"
    type: "eventbrite"
    url: "https://www.eventbrite.com/d/va--fredericksburg/free--events/?page=1"

  - name: "Bandsintown — Events near Fredericksburg"
    type: "bandsintown"
    url: "https://rest.bandsintown.com/events?location=Fredericksburg,VA&radius=50&date=upcoming&app_id=${BANDSINTOWN_APP_ID}"
